# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-08 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fairytales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='static/img')),
                ('text', models.TextField(max_length=10000)),
            ],
            options={
                'verbose_name': 'Сказка',
                'verbose_name_plural': 'Сказки',
            },
        ),
    ]
